#version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-jd24_web
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crmdatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  crm:
    image: haagenswe/gritcrm
    container_name: crm-container
    environment:
      DB_URL: jdbc:mysql://mysql/crmdatabase?useSSL=false
      DB_PASSWORD: rootpassword
      DB_USERNAME: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: gritcrm
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  db_data:
  pgdata:

networks:
  app-network:
    driver: bridge
